### ISSUE TITLE
in install doc, talk about openscraper/config/settings_example.py

### ISSUE THREAD

**Issue by DavidBruant** [entrepreneur-interet-general/OpenScraper#51]
Current Readme reads:

> update the `config/settings.py` file 

but it looks like one has to rename `openscraper/config/settings_example.py` to `openscraper/config/settings.py`

**Comment by JulienParis** [comment]
I changed the main run routine - commit https://github.com/entrepreneur-interet-general/OpenScraper/commit/6926f3b05c933f634f8cfa29b582d0adc675a798 - now you don't have to create a `settings_secret.py`file and should be able to run `main.py` with a simple : 
 
(run on port 8000)
`../openscraper$ python main.py`
equivalent to : 
`../openscraper$ python main.py --mode=default`

or 

(run on the port of your choice)
`../openscraper$ python main.py --port=8001`

**Comment by JulienParis** [comment]
resolved with commit : https://github.com/entrepreneur-interet-general/OpenScraper/commit/a5ded0f465b2c5b9f3dd2c6cedc43f4f85cf367e
