### ISSUE TITLE
What is app_scrapnado ?

### ISSUE THREAD

**Issue by DavidBruant** [entrepreneur-interet-general/OpenScraper#52]
Current readme reads:

> run app from $ ~/../app_scrapnado

But it's not clear what this is and it doesn't exist on my machine even after having done the other install steps

**Comment by JulienParis** [comment]
I changed this line in readme - commit https://github.com/entrepreneur-interet-general/OpenScraper/commit/6926f3b05c933f634f8cfa29b582d0adc675a798 - now it's just mentionning your local folder `./openscraper`
